dataapp/predictions/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField, IntegerField, StringField
from wtforms.validators import DataRequired, Length, NumberRange

class NyseForm(FlaskForm):
    myChoices = ["AMZN", "AAPL", "MSFT"]
    company_symbol = SelectField(u'Company Symbol', choices = myChoices, validators = [DataRequired()])
    open_val = IntegerField(u'Opening Value', validators = [DataRequired()])
    high_val = IntegerField(u'Highest Value', validators = [DataRequired()])
    low_val = IntegerField(u'Lowest Value', validators = [DataRequired()])
    submit = SubmitField('PREDICT')

class BeersForm(FlaskForm):
    beer_name = StringField('Beer Name',
                           validators=[DataRequired(), Length(min=2, max=20)], description="Enter the Beer Name")
    review_aroma = IntegerField(u'Aroma Review', validators = [DataRequired(), NumberRange(min = 0, max = 5)])
    review_pallete = IntegerField(u'Pallete Review', validators = [DataRequired(), NumberRange(min = 0, max = 5)])
    review_taste = IntegerField(u'Taste Review', validators = [DataRequired(), NumberRange(min = 0, max = 5)])
    review_appearance = IntegerField(u'Appearenvce Review', validators = [DataRequired(), NumberRange(min = 0, max = 5)])
    beer_abv = IntegerField(u'Beer ABV', validators = [DataRequired(), NumberRange(min = 0, max = 100)])
    submit = SubmitField('PREDICT')

dataapp/account/routes.py
from flask import escape, request, render_template, session, url_for, redirect, flash, Blueprint
from flask_login import login_user, logout_user

from dataapp import db, bcrypt
from dataapp.account.forms import RegistrationForm, LoginForm
from dataapp.models import users

account = Blueprint("account", __name__)

# New functions
@account.route("/register", methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hash_pass = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        new_user = users(form.username.data, form.email.data, hash_pass)
        db.session.add(new_user)
        db.session.commit()
        flash(f'Account has been created for {form.username.data} and you can now login!', 'success')
        return redirect(url_for('account.login'))
    return render_template('register.html', title='Register', form=form)


@account.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = users.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash(f"Login Successful! Welcome.", 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check your email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@account.route("/logout")
def logout():
    print("logging Out.")
    logout_user()
    return redirect(url_for('main.home'))

dataapp/main/routes.py
from flask import escape, request, render_template, url_for, redirect, flash, Blueprint
from flask_login import current_user, login_required

from dataapp.models import users, new_york, beer_review

main = Blueprint("main", __name__)

@main.route('/')
@main.route('/home')
def home():
    return render_template("home.html", title = "Home")

# Dashboard Page
@main.route('/dashboard', methods=["POST", "GET"])
@login_required
def dashboard():
    user = users.query.get(current_user.id)
    nyse = user.new_york
    beers = beer_review.query.filter_by(user_id=current_user.id).all()
    if not nyse and not beers:
        flash("No predictions done yet.", 'danger')
    return render_template("dashboard.html", post = nyse, beers = beers)    

# About page
@main.route('/about')
def about():
    return render_template("about.html", title = "Home")

dataapp/predictions/routes.py
from flask import escape, request, render_template, session, url_for, redirect, flash, Blueprint
from flask_login import current_user, login_required

from dataapp import db, nyse_stats, beer_stats
from dataapp.predictions.forms import NyseForm, BeersForm
from dataapp.support.regression import nyse_reg, beer_reg
from dataapp.models import new_york, beer_review, users
from dataapp.backend_tasks.tasks import nyse_db_add, beers_db_add

predict = Blueprint("predict", __name__)

@predict.route('/nyse', methods=["POST", "GET"])
@login_required
def nyse():
    form = NyseForm()
    if form.validate_on_submit():
        try:
            vals = list([form.company_symbol.data, form.open_val.data, form.high_val.data, form.low_val.data, current_user.id])
            job = nyse_db_add.delay(vals)
            nyse_stats.append(job)
            flash(f'Job Id: {job.task_id}', 'info')
            flash(f'Job submitted successfully. The predictions will be updated in the Dashboard once complete.', 'success')
            return redirect(url_for("main.home"))
        except Exception as e:
            flash(e, 'danger')
    return render_template("nyse.html", form = form)

# Beers
@predict.route('/beers', methods=["POST", "GET"])
@login_required
def beers():
    form = BeersForm()
    if form.validate_on_submit():
        try:
            beer_data = list([form.beer_name.data, form.review_aroma.data, form.review_pallete.data, form.review_taste.data, form.review_appearance.data, form.beer_abv.data, current_user.id])
            job = beers_db_add.delay(beer_data)
            beer_stats.append(job)
            flash(f'Job Id: {job.task_id}', 'info')
            flash(f'Job submitted successfully. The predictions will be updated in the Dashboard once complete.', 'success')
            return redirect(url_for("main.home"))
        except Exception as e:
            flash(e, 'danger')
    return render_template("beers.html", form = form)

@predict.route('/tasks')
@login_required
def tasks_page():
    return render_template("tasks.html", nyse_stats = nyse_stats, beer_stats = beer_stats)

dataapp/templates/about.html
{% extends "layout.html" %}

{% block content %}
    <h1>This APP is being Developed by GHOST</h1>
{% endblock content %}

dataapp/templates/beers.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4" style="color: snow;">BEERS REVIEW DATA</legend>
                            <div class="form-group" style="color: snow;">
                                {{ form.beer_name.label(class="form-control-label") }}
                                {% if form.beer_name.errors %}
                                    {{ form.beer_name(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.beer_name.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.beer_name(class="form-control form-control-lg", placeholder="British Empire") }}
                                    <!-- {{ form.beer_name(placeholder="British Empire")}} -->
                                {% endif %}
                            </div>
                            <div class="form-group" style="color: snow;">
                                {{ form.review_aroma.label(class="form-control-label") }}
                                {% if form.review_aroma.errors %}
                                    {{ form.review_aroma(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.review_aroma.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.review_aroma(class="form-control form-control-lg", placeholder="0 - 5") }}
                                {% endif %}
                            </div>
                            <div class="form-group" style="color: snow;">
                                {{ form.review_pallete.label(class="form-control-label") }}
                                {% if form.review_pallete.errors %}
                                    {{ form.review_pallete(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.review_pallete.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.review_pallete(class="form-control form-control-lg", placeholder="0 - 5") }}
                                {% endif %}
                            </div>
                            <div class="form-group" style="color: snow;">
                                {{ form.review_taste.label(class="form-control-label") }}
                                {% if form.review_taste.errors %}
                                    {{ form.review_taste(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.review_taste.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.review_taste(class="form-control form-control-lg", placeholder="0 - 5") }}
                                {% endif %}
                            </div>
                            <div class="form-group" style="color: snow;">
                                {{ form.review_appearance.label(class="form-control-label") }}
                                {% if form.review_appearance.errors %}
                                    {{ form.review_appearance(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.review_appearance.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.review_appearance(class="form-control form-control-lg", placeholder="0 - 5") }}
                                {% endif %}
                            </div>
                            <div class="form-group" style="color: snow;">
                                {{ form.beer_abv.label(class="form-control-label") }}
                                {% if form.beer_abv.errors %}
                                    {{ form.beer_abv(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.beer_abv.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.beer_abv(class="form-control form-control-lg", placeholder="0 - 100") }}
                                {% endif %}
                            </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-4"></div>
    </div> 
{% endblock content %}

dataapp/templates/dashboard.html
{% extends "layout.html" %}

{% block content %}
    <div class = "container-fluid" style="color: snow;">
        {% if post %}
            <div class="container border" style="border: 3px;">
                <h3 style="border: 1px;">NYSE DATA</h3>
                <br>
                <table class="table table-hove" id = "nyse_table">
                    <thead>
                        <tr>
                            <th><p align="center">Symbol</p></th>
                            <th><p align="center">Opening Value</p></th>
                            <th><p align="center">Highest Value</p></th>
                            <th><p align="center">Lowest Value</p></th>
                            <th><p align="center">PREDICTION</p></th>
                            <th><p align="center">Date and Time</p></th>
                            <th><p align="center">ID</p></th>
                        </tr>
                    </thead>
                    {% for predict in post %}
                        <tbody>
                            <tr>
                                <th><p align="center">{{predict.company_symbol}}</p></th>
                                <th><p align="center">{{predict.open_val}}</p></th>
                                <th><p align="center">{{predict.high_val}}</p></th>
                                <th><p align="center">{{predict.low_val}}</p></th>
                                <th><p align="center">{{predict.close_prediction}}</p></th>
                                <th><p align="center">{{predict.date_time}}</p></th>
                                <th><p align="center">{{predict.id}}</p></th>
                            </tr>
                        </tbody>
                    {% endfor %}
                </table>
            </div>
            <script>
                $(function(){
                  $("#nyse_table").dataTable();
                })
            </script>
        {% endif %}
        <br>
        <br>
        {% if beers %}
            <div class="container border">
                <h3>BEER REVIEWS</h3>
                <br>
                <table class="table table-hove" id = "beers_table">
                    <thead> 
                        <tr>
                            <th><p align="center">Beer Name</p></th>
                            <th><p align="center">Aroma Review</p></th>
                            <th><p align="center">Pallete Review</p></th>
                            <th><p align="center">Taste Review</p></th>
                            <th><p align="center">Apprearence Review</p></th>
                            <th><p align="center">Beer ABV</p></th>
                            <th><p align="center">PREDICTION</p></th>
                            <th><p align="center">Date and Time</p></th>
                            <th><p align="center">ID</p></th>
                        </tr>
                    </thead>   
                    {% for beer in beers %}
                        <tbody>
                            <tr>
                                <th><p align="center">{{beer.beer_name}}</p></th>
                                <th><p align="center">{{beer.review_aroma}}</p></th>
                                <th><p align="center">{{beer.review_pallete}}</p></th>
                                <th><p align="center">{{beer.review_taste}}</p></th>
                                <th><p align="center">{{beer.review_appearance}}</p></th>
                                <th><p align="center">{{beer.beer_abv}}</p></th>
                                <th><p align="center">{{beer.prediction_review}}</p></th>
                                <th><p align="center">{{beer.date_time}}</p></th>
                                <th><p align="center">{{beer.id}}</p></th>
                            </tr>
                        </tbody>
                    {% endfor %}
                </table>
            </div>
            <script>
                $(function(){
                  $("#beers_table").dataTable();
                })
            </script>
        {% endif %}
    </div>

{% endblock content %}

dataapp/templates/home.html
{% extends "layout.html" %}

{% block content %}
    <br>
    <div class = "container border-bottom mb-4">
        <h4 style="width: 400px; height: 70px; align-items: center; padding: 5px; color: snow;">Click on the Image to Access the predictions</h4>
    </div>
    <br>
    <br>
    <div class = "jumbotron">
        <div class = "container border-bottom mb-4">
            <h4 class="bg-info" style="width: 300px; height: 40px; align-items: center; padding: 5px;">Regression Models</h4>
        </div>
        <br>
        <div class = "row">
            <div class = "col-md-6">
                <p align="center" style="font-size: 20px;">New York Stock Exchange Dataset</p>
                <a href="{{ url_for('predict.nyse') }}"><img class="img-responsive img-rounded" src="https://raw.githubusercontent.com/AAbhishekReddy/data-app/master/support_models/images/nyse.jpg" alt="NYSE data" width="400" height="250"></a>
            </div>
            <div class = "col-md-6">
                <p align="center" style="font-size: 20px;">Beer Review Dataset</p>
                <a href="{{ url_for('predict.beers') }}"><img src="https://raw.githubusercontent.com/AAbhishekReddy/data-app/master/support_models/images/craft-beer.jpg" alt="NYSE data" width="400" height="250"></a>
            </div>
        </div>
    </div>
{% endblock content %}

dataapp/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">


    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js" defer></script>

    {% if title %}
        <title>Data App - {{ title }}</title>
    {% else %}
        <title>Data App</title>
    {% endif %}
</head>
<body style="background-color: rgb(65, 65, 65);">
    <div class="container jumbotron"  align="center">
        <h1 class = "border-bottom" style="color: rgb(65, 65, 65);"><a href="{{ url_for('main.home') }}">FLASK BASED DATA APP</a></h1>
        <nav class="navbar navbar-default navbar-fixed-top"></nav>
            <div class="container">
                <ul>
                    <li><a href="{{ url_for('main.home') }}">Home</a></li>
                    <li><a href="{{ url_for('main.dashboard') }}">Dashboard</a></li>
                    <li><a href="{{ url_for('predict.tasks_page') }}">Tasks</a></li>
                    <li><a href="/api/doc" style="background-color: rgb(212, 149, 77)">API (swagger docs)</a></li>
                    
                    <li style="float:right"><a class="active" style="background-color: rgb(48, 138, 211)" href="{{ url_for('main.about') }}">About</a></li>

                    {% if current_user.is_authenticated %}
                        <li style="float:right"><a class="active" style="background-color: rgba(116, 114, 114, 0.514);" href="{{ url_for('account.logout') }}">Logout</a></li>
                        <li style="float:right"><a class="active" style="background-color: rgb(175, 175, 175); color: navy;" href="#">{{current_user.name}}</a></li>
                    {% else %}
                    <li style="float:right"><a class="active" style="background-color: rgb(48, 138, 211)" href="{{ url_for('account.login') }}">Login</a></li>
                    <li style="float:right"><a class="active" style="background-color: rgb(48, 138, 211)" href="{{ url_for('account.register') }}">Register</a></li>
                    {% endif %}

                    {% block username %} {% endblock username %}
                </ul>
            </div>
        </nav>
    </div>

    <div class="container" align='center'>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
        {% block content %}{% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

dataapp/templates/login.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4" style="color: snow;">LOG IN</legend>
                        <div class="form-group" style="color: snow;">
                            {{ form.email.label(class="form-control-label") }}
                            {% if form.email.errors %}
                                {{ form.email(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.email(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group" style="color: snow;">
                            {{ form.password.label(class="form-control-label") }}
                            {% if form.password.errors %}
                                {{ form.password(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.password.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.password(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>
                </form>
            </div>
            <div class="border-top pt-3">
                <small class="text-muted" style="color: snow;">
                    Need An Account? <a class="ml-2" href="{{ url_for('account.register') }}">Sign Up Now</a>
                </small>
            </div>
        </div>
        <div class="col-md-4"></div>
    </div>
    
{% endblock content %}

dataapp/templates/nyse.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4" style="color: snow;">NYSE DATA</legend>
                        <div class="form-group" style="color: snow;">
                            {{ form.company_symbol.label(class="form-control-label") }}
                            {% if form.company_symbol.errors %}
                                {{ form.company_symbol(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.company_symbol.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.company_symbol(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group" style="color: snow;">
                            {{ form.open_val.label(class="form-control-label") }}
                            {% if form.open_val.errors %}
                                {{ form.open_val(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.open_val.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.open_val(class="form-control form-control-lg", value = 100) }}
                            {% endif %}
                        </div>
                        <div class="form-group" style="color: snow;">
                            {{ form.high_val.label(class="form-control-label") }}
                            {% if form.high_val.errors %}
                                {{ form.high_val(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.high_val.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.high_val(class="form-control form-control-lg", value = 150) }}
                            {% endif %}
                        </div>
                        <div class="form-group" style="color: snow;">
                            {{ form.low_val.label(class="form-control-label") }}
                            {% if form.low_val.errors %}
                                {{ form.low_val(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.low_val.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.low_val(class="form-control form-control-lg", value = 222) }}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-4"></div>
    </div> 
{% endblock content %}

dataapp/templates/tasks.html
{% extends "layout.html" %}

{% block content %}
    <div class = "container-fluid" style="color: snow;">
        {% if nyse_stats or beer_stats %}
            <h4>Refresh the page to check if the status has changed.</h4>
            <p><a href="{{ url_for('predict.tasks_page') }}">CLICK HERE TO REFRESH</a></p>
            {% if nyse_stats %}
                <div class="container border" style="border: 3px;">
                    <h3 style="border: 1px;">NYSE Jobs</h3>
                    <br>
                    <table class="table table-hove" id = "nyse_jobs">
                        <thead>
                            <tr>
                                <th><p align="center">Task Id</p></th>
                                <th><p align="center">Task Status</p></th>
                            </tr>
                        </thead>
                        {% for stats in nyse_stats %}
                            <tbody>
                                <tr>
                                    <th><p align="center">{{stats.task_id}}</p></th>
                                    <th><p align="center">{{stats.status}}</p></th>
                                </tr>
                            </tbody>
                        {% endfor %}
                    </table>
                </div>
                <script>
                    $(function(){
                    $("#nyse_jobs").dataTable();
                    })
                </script>
            {% endif %}

            <br>
            <br>

            {% if beer_stats %}
                <div class="container border" style="border: 3px;">
                    <h3 style="border: 1px;">Beer Review Jobs</h3>
                    <br>
                    <table class="table table-hove" id = "beer_jobs">
                        <thead>
                            <tr>
                                <th><p align="center">Task Id</p></th>
                                <th><p align="center">Task Status</p></th>
                            </tr>
                        </thead>
                        {% for stats in beer_stats %}
                            <tbody>
                                <tr>
                                    <th><p align="center">{{stats.task_id}}</p></th>
                                    <th><p align="center">{{stats.status}}</p></th>
                                </tr>
                            </tbody>
                        {% endfor %}
                    </table>
                </div>
                <script>
                    $(function(){
                    $("#beer_jobs").dataTable();
                    })
                </script>
            {% endif %}
        {% else %}
                <h2>No submitted jobs in this session.</h2>
        {% endif %}
    </div>
    
{% endblock content %}